"""adding column in the leave table

Revision ID: 00b0fa0b286e
Revises: c7d84dc8491a
Create Date: 2025-05-22 16:09:16.232319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00b0fa0b286e'
down_revision: Union[str, None] = 'c7d84dc8491a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('reviewer_id', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key(None, 'leaves', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'reviewer_id')
    # ### end Alembic commands ###
