"""adding time tracker table in the database

Revision ID: 12b09a0da68f
Revises: d4c561974063
Create Date: 2025-06-05 16:47:27.871818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12b09a0da68f'
down_revision: Union[str, None] = 'd4c561974063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TimeTracker',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('punch_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('punch_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TimeTracker')
    # ### end Alembic commands ###
