"""removing email passwordcolumn from the org table 

Revision ID: 1458f8a401b9
Revises: f59efc4a0bf3
Create Date: 2025-05-28 15:42:11.028273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1458f8a401b9'
down_revision: Union[str, None] = 'f59efc4a0bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_email', table_name='organizations')
    op.drop_constraint('organizations_ibfk_1', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'password')
    op.drop_column('organizations', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('role_id', mysql.VARCHAR(length=512), nullable=False))
    op.add_column('organizations', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('organizations', sa.Column('email', mysql.VARCHAR(length=90), nullable=True))
    op.create_foreign_key('organizations_ibfk_1', 'organizations', 'roles', ['role_id'], ['id'])
    op.create_index('ix_organizations_email', 'organizations', ['email'], unique=True)
    # ### end Alembic commands ###
