"""adding first_name and last_name column in user table

Revision ID: 176e8a4985b0
Revises: 104d59cbf057
Create Date: 2025-05-20 13:19:28.566044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '176e8a4985b0'
down_revision: Union[str, None] = '104d59cbf057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leaves', 'status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'),
               type_=sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='leavestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('leaves', 'status',
               existing_type=sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='leavestatus'),
               type_=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    # ### end Alembic commands ###
