"""removing is active from the table and adding updated at

Revision ID: 2b648ecea976
Revises: ca9a7c579cd9
Create Date: 2025-06-04 12:01:13.174671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b648ecea976'
down_revision: Union[str, None] = 'ca9a7c579cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('departments', 'updated_at')
    # ### end Alembic commands ###
