"""add permission and updated_at to roles

Revision ID: 352e3e92ea6b
Revises: 9b0707c4e9df
Create Date: 2025-05-08 16:54:06.355219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352e3e92ea6b'
down_revision: Union[str, None] = '9b0707c4e9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.JSON(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'permission')
    # ### end Alembic commands ###
