"""removing updated at from the department table

Revision ID: 41433fc38e0a
Revises: 2b648ecea976
Create Date: 2025-06-04 12:34:58.349498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41433fc38e0a'
down_revision: Union[str, None] = '2b648ecea976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
