"""fisrt commit

Revision ID: 5a7d30ffda8c
Revises: 
Create Date: 2025-05-06 16:11:24.452799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a7d30ffda8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('hash_password', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bookmarks',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=True),
    sa.Column('short_code', sa.String(length=10), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookmark_origin_url', 'bookmarks', ['origin_url'], unique=False, mysql_prefix='', mysql_length=512)
    op.create_index(op.f('ix_bookmarks_short_code'), 'bookmarks', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_short_code'), table_name='bookmarks')
    op.drop_index('ix_bookmark_origin_url', table_name='bookmarks', mysql_prefix='', mysql_length=512)
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
