"""create roles table

Revision ID: 60a5c228e455
Revises: 68f762ba038c
Create Date: 2025-05-16 13:55:22.049942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60a5c228e455'
down_revision: Union[str, None] = '68f762ba038c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.JSON(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('roles', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_index('role_type', table_name='roles')
    op.create_index(op.f('ix_roles_role_type'), 'roles', ['role_type'], unique=True)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=90),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=90),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_role_type'), table_name='roles')
    op.create_index('role_type', 'roles', ['role_type'], unique=True)
    op.alter_column('roles', 'id',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'permission')
    # ### end Alembic commands ###
