"""create table

Revision ID: 68f762ba038c
Revises: a93958c3e882
Create Date: 2025-05-15 16:33:07.936741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68f762ba038c'
down_revision: Union[str, None] = 'a93958c3e882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_role_type'), 'roles', ['role_type'], unique=True)
    op.drop_index('ix_bookmark_origin_url', table_name='bookmarks', mysql_length={'origin_url': 512})
    op.drop_index('ix_bookmarks_short_code', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.add_column('users', sa.Column('role_id', mysql.VARCHAR(length=512), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.create_table('bookmarks',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('origin_url', mysql.TEXT(), nullable=True),
    sa.Column('short_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('visit_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bookmarks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_bookmarks_short_code', 'bookmarks', ['short_code'], unique=True)
    op.create_index('ix_bookmark_origin_url', 'bookmarks', ['origin_url'], unique=False, mysql_length={'origin_url': 512})
    op.drop_index(op.f('ix_roles_role_type'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
