"""adding column in the table

Revision ID: 6d22269dccff
Revises: eef2af887286
Create Date: 2025-05-17 11:33:07.584030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d22269dccff'
down_revision: Union[str, None] = 'eef2af887286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('leave_type', sa.String(length=50), nullable=False))
    op.add_column('leaves', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('leaves', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'end_date')
    op.drop_column('leaves', 'start_date')
    op.drop_column('leaves', 'leave_type')
    # ### end Alembic commands ###
