"""Add password column to users

Revision ID: 847f9fc66ec6
Revises: 5a7d30ffda8c
Create Date: 2025-05-07 12:28:47.120494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '847f9fc66ec6'
down_revision: Union[str, None] = '5a7d30ffda8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', mysql.VARCHAR(length=512), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
