"""adding columns in the organization table

Revision ID: ad554a97225c
Revises: 0c930ac08b3c
Create Date: 2025-06-04 12:42:06.672167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad554a97225c'
down_revision: Union[str, None] = '0c930ac08b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('gst_number', mysql.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'gst_number')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'address')
    # ### end Alembic commands ###
