"""adding leave type in the column

Revision ID: c0cc1e3c9724
Revises: 00b0fa0b286e
Create Date: 2025-05-23 16:42:40.512075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0cc1e3c9724'
down_revision: Union[str, None] = '00b0fa0b286e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leaves_ibfk_2', 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'reviewer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('reviewer_id', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('leaves_ibfk_2', 'leaves', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###
