"""Add org_type_id foreign key to organizations

Revision ID: c0ee0aacf7d0
Revises: f4b28a3126be
Create Date: 2025-06-18 11:10:03.337882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0ee0aacf7d0'
down_revision: Union[str, None] = 'f4b28a3126be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'org_type_id',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.create_foreign_key(None, 'organizations', 'organization_type', ['org_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.alter_column('organizations', 'org_type_id',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
