"""add reviewer_id to leaves

Revision ID: ca5b1f089cd5
Revises: 04d310894439
Create Date: 2025-05-26 12:15:21.217361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca5b1f089cd5'
down_revision: Union[str, None] = '04d310894439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('reviewer_id', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key(None, 'leaves', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'reviewer_id')
    # ### end Alembic commands ###
