"""adding email and password in the org table

Revision ID: e63b91f61a3e
Revises: c0ee0aacf7d0
Create Date: 2025-06-18 11:30:52.205505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63b91f61a3e'
down_revision: Union[str, None] = 'c0ee0aacf7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email', sa.String(length=90), nullable=True))
    op.add_column('organizations', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_column('organizations', 'password')
    op.drop_column('organizations', 'email')
    # ### end Alembic commands ###
