"""Adding organization type table in the database

Revision ID: f4b28a3126be
Revises: 83c611bce11a
Create Date: 2025-06-18 10:32:25.811771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4b28a3126be'
down_revision: Union[str, None] = '83c611bce11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_type',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('org_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_type')
    )
    op.drop_column('organizations', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('industry', mysql.VARCHAR(length=100), nullable=True))
    op.drop_table('organization_type')
    # ### end Alembic commands ###
