"""adding org table in the database

Revision ID: f59efc4a0bf3
Revises: 1da62003a53a
Create Date: 2025-05-27 11:51:23.058741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f59efc4a0bf3'
down_revision: Union[str, None] = '1da62003a53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('role_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('org_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_name')
    )
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
